version: "3.8"

services:
  frontend:
    build: ./frontend/devDockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/frontend
    command: "yarn start"

  backend:
    build: ./backend
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
