version: "3.8"
volumes:
  build_folder: null

services:
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: "*"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    volumes:
      - ./frontend/:/frontend
      - build_folder:/frontend/build
    tty: true

  backend:
    build: ./backend
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_folder:/var/www/frontend
    depends_on:
      - frontend

  mysqldb:
    build: ./db
    env_file:
      - "./db/db.env"
    ports:
      - "8989:3306"
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
